name = "dgemua"
description = "DG MV-Class System Emulator"
version = "0.1.0-dev"

authors = ["Stephen Merrony"]
maintainers = ["Stephen Merrony <merrony@gmail.com>"]
maintainers-logins = ["SMerrony"]
licenses = "MIT"
website = ""
tags = []

executables = ["vsemua", "mvemua"]

project-files = ["vsemua.gpr", "mvemua.gpr"]
